version: '3.6'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_product'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306