spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_product
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db.changelog/dbchangelog.xml

security:
  jwt:
    token:
      secret-key: HEHwyDSISxEAmTjZUQtmHCo3IftFWKdLck0xoJ0ZA3Pk9j0E481j3UDJ6Bn555p
      expire-length: 86400000 # 1 Day
      prefix: Bearer
      header: Authorization

server:
  servlet:
    session:
      tracking-modes: cookie
